Repository Heroineeee/BE, pull requests merged in 2025-07, with the labels that each got.

#79 [Scrum - 175] Feat : 커뮤니티 게시글 조회 시 응답 필드 추가
  src/main/java/com/kkinikong/be/community/dto/request/CommunityPostRequest.java
  src/main/java/com/kkinikong/be/community/dto/response/CommunityPostInfoResponse.java
  src/main/java/com/kkinikong/be/community/repository/CommunityPostImageRepository.java
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
Labels: :sparkles: Feature

#83 [SCRUM-287] Feat : 내가 작성한 리뷰 페이지에 가맹점명 추가
  src/main/java/com/kkinikong/be/user/dto/response/MypageReviewResponse.java
Labels: :sparkles: Feature

#87 [SCRUM-287] Refactor : 페이징에 totalCount 추가
  src/main/java/com/kkinikong/be/global/response/PageResponse.java
  src/main/java/com/kkinikong/be/store/repository/storescrap/StoreScrapRepository.java
  src/main/java/com/kkinikong/be/user/controller/MypageController.java
  src/main/java/com/kkinikong/be/user/service/MypageService.java
Labels: :recycle: Refactor, :sparkles: Feature

#88 [SCRUM-245] Fix : 한글 깨짐 현상 해결 및 redirectUrl에서 null 값 해결
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
  src/main/java/com/kkinikong/be/notification/infrastructure/sse/SseNotificationService.java
Labels: :bug: Bug

#89 [SCRUM-245] Fix : 답글 알림이 커뮤니티 게시글 작성자에게 가는 문제 해결
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
Labels: :bug: Bug

#90 [SCRUM-245] Fix : controller에 utf-8 설정 추가
  src/main/java/com/kkinikong/be/notification/controller/NotificationController.java
Labels: :bug: Bug

#92 [SCRUM-287] Fix : redis 메시지 직렬화/역직렬화 방식 개선 및 한글 깨짐 문제 해결
  src/main/java/com/kkinikong/be/notification/infrastructure/pubsub/NotificationPublisher.java
  src/main/java/com/kkinikong/be/notification/infrastructure/pubsub/NotificationSubscriber.java
Labels: :bug: Bug

#93 [SCRUM-190] Feat: 검색 조건 수정
  src/main/java/com/kkinikong/be/community/exception/errorcode/CommunityErrorCode.java
  src/main/java/com/kkinikong/be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kkinikong/be/opensearch/controller/OpenSearchAdminController.java
  src/main/java/com/kkinikong/be/opensearch/exception/OpenSearchException.java
  src/main/java/com/kkinikong/be/opensearch/exception/errorcode/OpenSearchErrorCode.java
  src/main/java/com/kkinikong/be/opensearch/service/OpenSearchService.java
Labels: :recycle: Refactor, :sparkles: Feature

#94 [SCRUM-287] Fix : 내가 좋아요 누른 게시글 조회에서 '게시글' 기준 최신순 정렬 하도록 수정
  src/main/java/com/kkinikong/be/community/repository/CommunityPostLikeRepository.java
  src/main/java/com/kkinikong/be/user/service/MypageService.java
Labels: :bug: Bug

#100 [SCRUM-150] Refeator : 커뮤니티 게시글 글자수 제한 완화
  src/main/java/com/kkinikong/be/community/domain/CommunityPost.java
  src/main/java/com/kkinikong/be/community/dto/request/CommunityPostRequest.java
  src/main/java/com/kkinikong/be/community/dto/request/CommunityPostUpdateRequest.java
Labels: :recycle: Refactor

#103 [SCRUM-150] Fix: 커뮤니티 이미지 썸네일 Null로 들어가는 문제 수정
  src/main/java/com/kkinikong/be/community/domain/CommunityPost.java
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
Labels: :ambulance: !HOTFIX

#102 [Refactor] 알림 로직 비동기 이벤트 방식으로 리팩토링
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
  src/main/java/com/kkinikong/be/convenience/service/ConvenienceService.java
  src/main/java/com/kkinikong/be/global/config/AsyncConfig.java
  src/main/java/com/kkinikong/be/notification/event/NotificationEvent.java
  src/main/java/com/kkinikong/be/notification/event/NotificationEventListener.java
  src/main/java/com/kkinikong/be/notification/event/payload/CommentEvent.java
  src/main/java/com/kkinikong/be/notification/event/payload/CommentLikeEvent.java
  src/main/java/com/kkinikong/be/notification/event/payload/CommentReplyEvent.java
  src/main/java/com/kkinikong/be/notification/event/payload/CommunityLikeEvent.java
  src/main/java/com/kkinikong/be/notification/event/payload/ConvenienceInfoEvent.java
  src/main/java/com/kkinikong/be/notification/infrastructure/pubsub/NotificationPublisher.java
  src/main/java/com/kkinikong/be/notification/infrastructure/sse/SseNotificationService.java
Labels: :recycle: Refactor

#105 [SCRUM-336] Refact: 가맹점 리뷰 중복 수정
  src/main/java/com/kkinikong/be/review/service/ReviewService.java
Labels: :sparkles: Feature

#107 [SCRUM-338] Refactor : 위경도 기반 반경 내 가맹점 탐색 방식에서 Bounding Box 활용하도록 수정
  build.gradle
  src/main/java/com/kkinikong/be/store/domain/Store.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustomImpl.java
  src/main/java/com/kkinikong/be/store/repository/storeupload/StoreJdbcRepositoryImpl.java
Labels: :recycle: Refactor
