Repository Heroineeee/BE, pull requests merged in 2025-05, with the labels that each got.

#9 [Feat] 배포 자동화를 진행한다 (SCRUM-19)
  .github/workflows/kkinikong-be-cd.yml
  .github/workflows/kkinikong-be-ci.yml
  .gitignore
  Dockerfile
  src/main/resources/application.yml
Labels: :sparkles: Feature

#8 [Feat] csv 파일을 db에 넣기 위한 작업
  build.gradle
  src/main/java/com/kkinikong/be/batch/config/StoreCsvJobConfig.java
  src/main/java/com/kkinikong/be/batch/controller/BatchController.java
  src/main/java/com/kkinikong/be/batch/dto/StoreCsv.java
  src/main/java/com/kkinikong/be/batch/exception/BatchException.java
  src/main/java/com/kkinikong/be/batch/exception/errorcode/BatchErrorCode.java
  src/main/java/com/kkinikong/be/batch/processor/CategoryMapper.java
  src/main/java/com/kkinikong/be/batch/processor/StoreCsvProcessor.java
  src/main/java/com/kkinikong/be/batch/reader/StoreCsvReader.java
  src/main/java/com/kkinikong/be/batch/service/BatchService.java
  src/main/java/com/kkinikong/be/batch/util/FileUtil.java
  src/main/java/com/kkinikong/be/batch/writer/StoreCsvWriter.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/java/com/kkinikong/be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kkinikong/be/post/domain/Post.java
  src/main/java/com/kkinikong/be/post/repository/PostRepository.java
  src/main/java/com/kkinikong/be/post/service/PostService.java
  src/main/java/com/kkinikong/be/report/controller/ReportController.java
  src/main/java/com/kkinikong/be/report/domain/Report.java
  src/main/java/com/kkinikong/be/report/domain/type/CommonReportReason.java
  src/main/java/com/kkinikong/be/report/domain/type/ReportType.java
  src/main/java/com/kkinikong/be/report/domain/type/StoreReportReason.java
  src/main/java/com/kkinikong/be/report/exception/ReportException.java
  src/main/java/com/kkinikong/be/report/exception/errorcode/ReportErrorCode.java
  src/main/java/com/kkinikong/be/report/respository/ReportRepository.java
  src/main/java/com/kkinikong/be/report/service/ReportService.java
  src/main/java/com/kkinikong/be/review/controller/ReviewController.java
  src/main/java/com/kkinikong/be/review/domain/Review.java
  src/main/java/com/kkinikong/be/review/domain/ReviewImage.java
  src/main/java/com/kkinikong/be/review/domain/ReviewTag.java
  src/main/java/com/kkinikong/be/review/domain/mapping/ReviewTagMap.java
  src/main/java/com/kkinikong/be/review/domain/type/TagCategory.java
  src/main/java/com/kkinikong/be/review/exception/ReviewException.java
  src/main/java/com/kkinikong/be/review/exception/errorcode/ReviewErrorCode.java
  src/main/java/com/kkinikong/be/review/repository/ReviewRepository.java
  src/main/java/com/kkinikong/be/review/service/ReviewService.java
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/domain/Store.java
  src/main/java/com/kkinikong/be/store/domain/StoreScrap.java
  src/main/java/com/kkinikong/be/store/domain/type/Category.java
  src/main/java/com/kkinikong/be/store/exception/StoreException.java
  src/main/java/com/kkinikong/be/store/exception/errorcode/StoreErrorCode.java
  src/main/java/com/kkinikong/be/store/repository/StoreRepository.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
  src/main/java/com/kkinikong/be/user/domain/User.java
  src/main/resources/application.yml
  src/test/java/com/kkinikong/be/batch/processor/StoreCsvProcessorTest.java
  src/test/java/com/kkinikong/be/batch/reader/StoreCsvReaderTest.java
  src/test/java/com/kkinikong/be/batch/writer/StoreCsvWriterTest.java
Labels: :sparkles: Feature

#18 [Feat] 가맹점 상세보기 및 수정 요청 구현 (SCRUM-8)
  .github/workflows/kkinikong-be-ci.yml
  build.gradle
  docker-compose.yml
  src/main/java/com/kkinikong/be/KkinikongBeApplication.java
  src/main/java/com/kkinikong/be/cache/controller/CacheController.java
  src/main/java/com/kkinikong/be/cache/service/CacheService.java
  src/main/java/com/kkinikong/be/global/config/CommonConfig.java
  src/main/java/com/kkinikong/be/global/config/RedisCacheConfig.java
  src/main/java/com/kkinikong/be/global/config/RedisConfig.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/java/com/kkinikong/be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kkinikong/be/report/controller/ReportController.java
  src/main/java/com/kkinikong/be/report/domain/Report.java
  src/main/java/com/kkinikong/be/report/domain/type/StoreReportReason.java
  src/main/java/com/kkinikong/be/report/dto/request/ReportStoreRequest.java
  src/main/java/com/kkinikong/be/report/exception/errorcode/ReportErrorCode.java
  src/main/java/com/kkinikong/be/report/respository/ReportRepository.java
  src/main/java/com/kkinikong/be/report/service/ReportService.java
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreExternalLinkResponse.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreInfoResponse.java
  src/main/java/com/kkinikong/be/store/exception/errorcode/StoreErrorCode.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepository.java
  src/main/java/com/kkinikong/be/store/service/StoreCacheService.java
  src/main/java/com/kkinikong/be/store/service/StoreScheduledService.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
  src/main/java/com/kkinikong/be/store/util/google/StoreGoogleApiClient.java
  src/main/java/com/kkinikong/be/store/util/kakao/StoreKakaoApiClient.java
  src/main/java/com/kkinikong/be/user/exception/errorcode/UserErrorCode.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
Labels: :sparkles: Feature

#21 [Feat] 가맹점 스크랩 API 구현
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/java/com/kkinikong/be/global/exception/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/domain/Store.java
  src/main/java/com/kkinikong/be/store/domain/StoreScrap.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreScrapResponse.java
  src/main/java/com/kkinikong/be/store/exception/errorcode/StoreErrorCode.java
  src/main/java/com/kkinikong/be/store/repository/storescrap/StoreScrapRepository.java
  src/main/java/com/kkinikong/be/store/repository/storescrap/StoreScrapRepositoryCustom.java
  src/main/java/com/kkinikong/be/store/repository/storescrap/StoreScrapRepositoryCustomImpl.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
Labels: :sparkles: Feature

#25 [Refactor] CSV 파일 db에 넣기 리팩토링
  .gitignore
  build.gradle
  src/main/java/com/kkinikong/be/batch/config/StoreCsvJobConfig.java
  src/main/java/com/kkinikong/be/batch/controller/BatchController.java
  src/main/java/com/kkinikong/be/batch/dto/StoreCsv.java
  src/main/java/com/kkinikong/be/batch/exception/BatchException.java
  src/main/java/com/kkinikong/be/batch/exception/errorcode/BatchErrorCode.java
  src/main/java/com/kkinikong/be/batch/processor/CategoryMapper.java
  src/main/java/com/kkinikong/be/batch/processor/StoreCsvProcessor.java
  src/main/java/com/kkinikong/be/batch/reader/StoreCsvReader.java
  src/main/java/com/kkinikong/be/batch/service/BatchService.java
  src/main/java/com/kkinikong/be/batch/util/FileUtil.java
  src/main/java/com/kkinikong/be/batch/writer/StoreCsvWriter.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/java/com/kkinikong/be/global/exception/handler/CustomAccessDeniedHandler.java
  src/main/java/com/kkinikong/be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kkinikong/be/store/controller/StoreUploadController.java
  src/main/java/com/kkinikong/be/store/domain/type/Category.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreUploadResponse.java
  src/main/java/com/kkinikong/be/store/exception/errorcode/StoreErrorCode.java
  src/main/java/com/kkinikong/be/store/repository/storeupload/StoreJdbcRepository.java
  src/main/java/com/kkinikong/be/store/repository/storeupload/StoreJdbcRepositoryImpl.java
  src/main/java/com/kkinikong/be/store/service/StoreUploadService.java
  src/main/java/com/kkinikong/be/user/utils/CustomUserDetailService.java
  src/main/java/com/kkinikong/be/user/utils/CustomUserDetails.java
  src/main/resources/application.yml
Labels: :recycle: Refactor

#26 [Hotfix] db에 한글 깨짐 오류
  build.gradle
Labels: :ambulance: !HOTFIX

#28 [Feat] 리뷰 관련 기능을 구현한다 (SCRUM-10)
  build.gradle
  src/main/java/com/kkinikong/be/global/config/S3Config.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/java/com/kkinikong/be/global/exception/errorcode/GlobalErrorCode.java
  src/main/java/com/kkinikong/be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kkinikong/be/global/response/PageResponse.java
  src/main/java/com/kkinikong/be/report/controller/ReportController.java
  src/main/java/com/kkinikong/be/report/dto/request/ReportRequest.java
  src/main/java/com/kkinikong/be/report/exception/errorcode/ReportErrorCode.java
  src/main/java/com/kkinikong/be/report/service/ReportService.java
  src/main/java/com/kkinikong/be/review/controller/ReviewController.java
  src/main/java/com/kkinikong/be/review/domain/Review.java
  src/main/java/com/kkinikong/be/review/domain/ReviewImage.java
  src/main/java/com/kkinikong/be/review/domain/ReviewTag.java
  src/main/java/com/kkinikong/be/review/domain/mapping/ReviewTagMap.java
  src/main/java/com/kkinikong/be/review/domain/type/Tag.java
  src/main/java/com/kkinikong/be/review/domain/type/TagCategory.java
  src/main/java/com/kkinikong/be/review/dto/request/ReviewRequest.java
  src/main/java/com/kkinikong/be/review/dto/response/ReviewItemResponse.java
  src/main/java/com/kkinikong/be/review/dto/response/ReviewListItemResponse.java
  src/main/java/com/kkinikong/be/review/dto/response/ReviewPostResponse.java
  src/main/java/com/kkinikong/be/review/exception/errorcode/ReviewErrorCode.java
  src/main/java/com/kkinikong/be/review/repository/ReviewRepository.java
  src/main/java/com/kkinikong/be/review/repository/review/ReviewRepository.java
  src/main/java/com/kkinikong/be/review/repository/reviewimage/ReviewImageCustomRepository.java
  src/main/java/com/kkinikong/be/review/repository/reviewimage/ReviewImageCustomRepositoryImpl.java
  src/main/java/com/kkinikong/be/review/repository/reviewimage/ReviewImageRepository.java
  src/main/java/com/kkinikong/be/review/repository/reviewtag/ReviewTagCustomRepository.java
  src/main/java/com/kkinikong/be/review/repository/reviewtag/ReviewTagCustomRepositoryImpl.java
  src/main/java/com/kkinikong/be/review/repository/reviewtag/ReviewTagRepository.java
  src/main/java/com/kkinikong/be/review/repository/reviewtag/ReviewTagRepositoryCustom.java
  src/main/java/com/kkinikong/be/review/repository/reviewtag/ReviewTagRepositoryImpl.java
  src/main/java/com/kkinikong/be/review/service/ReviewImageService.java
  src/main/java/com/kkinikong/be/review/service/ReviewService.java
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/domain/Store.java
  src/main/java/com/kkinikong/be/store/domain/StoreTagCount.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreInfoResponse.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreListItemResponse.java
  src/main/java/com/kkinikong/be/store/repository/storetag/StoreTagCountRepository.java
  src/main/java/com/kkinikong/be/store/repository/storetag/StoreTagCountRepositoryCustom.java
  src/main/java/com/kkinikong/be/store/repository/storetag/StoreTagCountRepositoryCustomImpl.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
  src/main/java/com/kkinikong/be/store/util/google/StoreGoogleApiClient.java
  src/main/java/com/kkinikong/be/util/exception/S3Exception.java
  src/main/java/com/kkinikong/be/util/exception/errorcode/S3ErrorCode.java
  src/main/java/com/kkinikong/be/util/service/S3FileUploader.java
  src/main/resources/application.yml
Labels: :sparkles: Feature

#30 [Refactor] 닉네임 등록 API 응답 수정
  src/main/java/com/kkinikong/be/user/controller/UserController.java
  src/main/java/com/kkinikong/be/user/dto/request/NicknameRequest.java
  src/main/java/com/kkinikong/be/user/dto/response/NicknameResponse.java
  src/main/java/com/kkinikong/be/user/service/UserService.java
Labels: :recycle: Refactor

#35 [Refactor] 가맹점 상세 정보 조회 위경도 추가
  src/main/java/com/kkinikong/be/store/dto/response/StoreInfoResponse.java
Labels: :recycle: Refactor

#29 [Feat] 가맹점 검색 기능 API 구현
  src/main/java/com/kkinikong/be/global/response/PageResponse.java
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreMapListItemResponse.java
  src/main/java/com/kkinikong/be/store/exception/errorcode/StoreErrorCode.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustom.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustomImpl.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
Labels: :recycle: Refactor, :sparkles: Feature

#37 [SCRUM-8] Feat : 가맹점 수정 요청 변경
  src/main/java/com/kkinikong/be/report/domain/Report.java
  src/main/java/com/kkinikong/be/report/exception/errorcode/ReportErrorCode.java
  src/main/java/com/kkinikong/be/report/respository/ReportRepository.java
  src/main/java/com/kkinikong/be/report/service/ReportService.java
Labels: :sparkles: Feature

#38 [Refactor] 가맹점 찾기 화면 리스트 조회/ 검색 통합 API 수정
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustom.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustomImpl.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
Labels: :recycle: Refactor

#39 [SCRUM-43] Feat : 가맹점 평점 리턴 형식 변경
  src/main/java/com/kkinikong/be/store/dto/response/StoreInfoResponse.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreListItemResponse.java
Labels: :sparkles: Feature

#36 [Feat] 구글/네이버 소셜 로그인 구현
  src/main/java/com/kkinikong/be/auth/dto/response/google/GoogleLoginResponse.java
  src/main/java/com/kkinikong/be/auth/dto/response/google/GoogleUserInfoResponse.java
  src/main/java/com/kkinikong/be/auth/dto/response/kakao/KakaoLoginResponse.java
  src/main/java/com/kkinikong/be/auth/dto/response/kakao/KakaoUserInfoResponse.java
  src/main/java/com/kkinikong/be/auth/dto/response/naver/NaverLoginResponse.java
  src/main/java/com/kkinikong/be/auth/dto/response/naver/NaverUserInfoResponse.java
  src/main/java/com/kkinikong/be/auth/service/strategy/GoogleLoginStrategy.java
  src/main/java/com/kkinikong/be/auth/service/strategy/KakaoLoginStrategy.java
  src/main/java/com/kkinikong/be/auth/service/strategy/NaverLoginStrategy.java
  src/main/java/com/kkinikong/be/auth/util/google/GoogleApiClient.java
  src/main/java/com/kkinikong/be/auth/util/kakao/KakaoApiClient.java
  src/main/java/com/kkinikong/be/auth/util/naver/NaverApiClient.java
Labels: :sparkles: Feature

#40 [Refactor] 가맹점 지도 화면 리스트/검색 통합 조회
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustom.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustomImpl.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: :recycle: Refactor

#41 [Feat] 메인페이지 조회수 높은 8개 가맹점 조회
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreCardResponse.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustom.java
  src/main/java/com/kkinikong/be/store/repository/store/StoreRepositoryCustomImpl.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
Labels: :sparkles: Feature

#42 [SCRUM-8] Feat : 가게 상세정보에 스크랩 여부 추가
  src/main/java/com/kkinikong/be/report/controller/ReportController.java
  src/main/java/com/kkinikong/be/store/controller/StoreController.java
  src/main/java/com/kkinikong/be/store/dto/response/StoreInfoResponse.java
  src/main/java/com/kkinikong/be/store/repository/storescrap/StoreScrapRepository.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
Labels: :sparkles: Feature

#43 [Feat] 편의점 정보 게시판 엔티티 작성
  src/main/java/com/kkinikong/be/convenience/domain/ConvenienceHelpful.java
  src/main/java/com/kkinikong/be/convenience/domain/ConveniencePost.java
  src/main/java/com/kkinikong/be/convenience/domain/type/Brand.java
  src/main/java/com/kkinikong/be/convenience/domain/type/Category.java
  src/main/java/com/kkinikong/be/convenience/exception/ConvenienceException.java
  src/main/java/com/kkinikong/be/convenience/exception/errorcode/ConvenienceErrorCode.java
  src/main/java/com/kkinikong/be/global/exception/handler/GlobalExceptionHandler.java
  src/main/java/com/kkinikong/be/user/domain/User.java
Labels: :sparkles: Feature

#44 [SCRUM-92] Feat : 편의점 제품명 추천 로직 구현
  src/main/java/com/kkinikong/be/convenience/controller/ConvenienceController.java
  src/main/java/com/kkinikong/be/convenience/dto/response/ConvenienceRecommendationResponse.java
  src/main/java/com/kkinikong/be/convenience/exception/errorcode/ConvenienceErrorCode.java
  src/main/java/com/kkinikong/be/convenience/repository/ConvenienceRepository.java
  src/main/java/com/kkinikong/be/convenience/service/ConvenienceService.java
  src/main/java/com/kkinikong/be/convenience/util/OpenAIApiClient.java
  src/main/java/com/kkinikong/be/convenience/util/dto/Message.java
  src/main/java/com/kkinikong/be/convenience/util/dto/OpenAIRequest.java
  src/main/java/com/kkinikong/be/convenience/util/dto/OpenAIResponse.java
  src/main/java/com/kkinikong/be/global/config/WebClientConfig.java
  src/main/resources/application.yml
Labels: :sparkles: Feature

#45 [Feat] 편의점 게시글 작성 및 삭제 API 구현
  src/main/java/com/kkinikong/be/convenience/controller/ConvenienceController.java
  src/main/java/com/kkinikong/be/convenience/domain/ConveniencePost.java
  src/main/java/com/kkinikong/be/convenience/domain/type/Brand.java
  src/main/java/com/kkinikong/be/convenience/dto/request/ConvenienceRequest.java
  src/main/java/com/kkinikong/be/convenience/dto/response/ConveniencePostResponse.java
  src/main/java/com/kkinikong/be/convenience/exception/errorcode/ConvenienceErrorCode.java
  src/main/java/com/kkinikong/be/convenience/service/ConvenienceService.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: :sparkles: Feature

#46 [Feat] 편의점 정보 게시글에 '올바른정보예요/잘못된정보예요' 설정 API 구현
  src/main/java/com/kkinikong/be/convenience/controller/ConvenienceController.java
  src/main/java/com/kkinikong/be/convenience/domain/ConvenienceHelpful.java
  src/main/java/com/kkinikong/be/convenience/domain/ConveniencePost.java
  src/main/java/com/kkinikong/be/convenience/dto/request/ConveniencePostInfoRequest.java
  src/main/java/com/kkinikong/be/convenience/dto/response/ConveniencePostInfoResponse.java
  src/main/java/com/kkinikong/be/convenience/exception/errorcode/ConvenienceErrorCode.java
  src/main/java/com/kkinikong/be/convenience/repository/ConvenienceHelpfulRepository.java
  src/main/java/com/kkinikong/be/convenience/service/ConvenienceService.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#47 [Feat] 사용자가 자주 가는 지역 설정 API 구현
  .DS_Store
  .gitignore
  src/main/java/com/kkinikong/be/user/controller/UserController.java
  src/main/java/com/kkinikong/be/user/domain/User.java
  src/main/java/com/kkinikong/be/user/dto/request/UserPlaceRequest.java
  src/main/java/com/kkinikong/be/user/service/UserService.java
Labels: :sparkles: Feature
