Repository Heroineeee/BE, pull requests merged in 2025-06, with the labels that each got.

#49 [SCRUM-98] Feat : 편의점 상세보기 구현
  src/main/java/com/kkinikong/be/convenience/controller/ConvenienceController.java
  src/main/java/com/kkinikong/be/convenience/domain/ConveniencePost.java
  src/main/java/com/kkinikong/be/convenience/dto/response/ConveniencePostDetailResponse.java
  src/main/java/com/kkinikong/be/convenience/service/ConvenienceService.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
Labels: :sparkles: Feature

#53 [SCRUM-160] Feat : 커뮤니티 좋아요 기능 구현
  src/main/java/com/kkinikong/be/community/controller/CommunityController.java
  src/main/java/com/kkinikong/be/community/domain/Comment.java
  src/main/java/com/kkinikong/be/community/domain/CommentLike.java
  src/main/java/com/kkinikong/be/community/domain/CommunityPost.java
  src/main/java/com/kkinikong/be/community/domain/CommunityPostLike.java
  src/main/java/com/kkinikong/be/community/dto/response/LikeToggleResponse.java
  src/main/java/com/kkinikong/be/community/repository/CommentLikeRepository.java
  src/main/java/com/kkinikong/be/community/repository/CommentRepository.java
  src/main/java/com/kkinikong/be/community/repository/CommunityPostLikeRepository.java
  src/main/java/com/kkinikong/be/community/repository/CommunityPostRepository.java
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/test/java/com/kkinikong/be/community/service/CommunityServiceTest.java
Labels: :sparkles: Feature

#56 [SCRUM-186] Feat : 마이페이지 관련 API 구현
  src/main/java/com/kkinikong/be/convenience/repository/ConvenienceRepository.java
  src/main/java/com/kkinikong/be/global/config/SecurityConfig.java
  src/main/java/com/kkinikong/be/review/repository/ReviewRepository.java
  src/main/java/com/kkinikong/be/store/repository/storescrap/StoreScrapRepository.java
  src/main/java/com/kkinikong/be/user/controller/MypageController.java
  src/main/java/com/kkinikong/be/user/dto/response/MypageReviewResponse.java
  src/main/java/com/kkinikong/be/user/dto/response/MypageStoreResponse.java
  src/main/java/com/kkinikong/be/user/service/MypageService.java
Labels: :sparkles: Feature

#57 [SCRUM-188] Feat : 회원 탈퇴 구현
  src/main/java/com/kkinikong/be/review/service/ReviewService.java
  src/main/java/com/kkinikong/be/store/repository/storescrap/StoreScrapRepository.java
  src/main/java/com/kkinikong/be/user/controller/UserController.java
  src/main/java/com/kkinikong/be/user/domain/User.java
  src/main/java/com/kkinikong/be/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/kkinikong/be/user/service/UserService.java
  src/main/java/com/kkinikong/be/user/utils/UserNicknameUtil.java
Labels: :sparkles: Feature

#58 [SCRUM-175] Feat : 커뮤니티 조회 관련 기능 구현
  src/main/java/com/kkinikong/be/community/controller/CommunityController.java
  src/main/java/com/kkinikong/be/community/domain/Comment.java
  src/main/java/com/kkinikong/be/community/domain/CommunityPost.java
  src/main/java/com/kkinikong/be/community/dto/request/CommunityCommentRequest.java
  src/main/java/com/kkinikong/be/community/dto/request/CommunityPostRequest.java
  src/main/java/com/kkinikong/be/community/dto/response/CommentListResponse.java
  src/main/java/com/kkinikong/be/community/dto/response/CommunityPostInfoResponse.java
  src/main/java/com/kkinikong/be/community/dto/response/CommunityPostListResponse.java
  src/main/java/com/kkinikong/be/community/dto/response/CommunityPostPopularResponse.java
  src/main/java/com/kkinikong/be/community/dto/response/CommunityPostPopularWrappingResponse.java
  src/main/java/com/kkinikong/be/community/repository/CommentRepository.java
  src/main/java/com/kkinikong/be/community/repository/CommunityPostRepository.java
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
  src/main/java/com/kkinikong/be/community/util/TimeUtil.java
  src/main/java/com/kkinikong/be/global/config/RedisCacheConfig.java
Labels: :sparkles: Feature

#60 [SCRUM-194] 유저가 설정한 자주 가는 지역의 위경도 불러오기
  src/main/java/com/kkinikong/be/user/controller/UserController.java
  src/main/java/com/kkinikong/be/user/dto/response/UserPlaceResponse.java
  src/main/java/com/kkinikong/be/user/service/UserService.java
Labels: :sparkles: Feature

#59 [SCRUM-175] Feat : 작성자 여부 추가 및 조회수 추가
  src/main/java/com/kkinikong/be/cache/service/CounterCacheService.java
  src/main/java/com/kkinikong/be/cache/service/ScheduledService.java
  src/main/java/com/kkinikong/be/cache/type/RedisKey.java
  src/main/java/com/kkinikong/be/community/controller/CommunityController.java
  src/main/java/com/kkinikong/be/community/domain/Comment.java
  src/main/java/com/kkinikong/be/community/domain/CommunityPost.java
  src/main/java/com/kkinikong/be/community/dto/response/CommentListResponse.java
  src/main/java/com/kkinikong/be/community/dto/response/CommunityPostInfoResponse.java
  src/main/java/com/kkinikong/be/community/dto/response/CommunityPostListResponse.java
  src/main/java/com/kkinikong/be/community/repository/CommunityPostRepository.java
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
  src/main/java/com/kkinikong/be/store/service/StoreCacheService.java
  src/main/java/com/kkinikong/be/store/service/StoreScheduledService.java
  src/main/java/com/kkinikong/be/store/service/StoreService.java
Labels: :sparkles: Feature

#64 [SCRUM-98] Refactor : 편의점 상세 조회 부분에 비회원도 조회 가능하도록 수정
  src/main/java/com/kkinikong/be/convenience/controller/ConvenienceController.java
  src/main/java/com/kkinikong/be/convenience/dto/response/ConveniencePostDetailResponse.java
  src/main/java/com/kkinikong/be/convenience/service/ConvenienceService.java
Labels: :recycle: Refactor, :sparkles: Feature

#65 [SCRUM-239] Refactor : 올바른정보예요/잘못된정보예요 수정
  src/main/java/com/kkinikong/be/convenience/service/ConvenienceService.java
Labels: :recycle: Refactor, :sparkles: Feature

#66 [SCRUM-241] Feat : 닉네임 수정 API 구현
  src/main/java/com/kkinikong/be/user/controller/UserController.java
  src/main/java/com/kkinikong/be/user/domain/User.java
  src/main/java/com/kkinikong/be/user/exception/errorcode/UserErrorCode.java
  src/main/java/com/kkinikong/be/user/service/UserService.java
Labels: :sparkles: Feature

#70 [SCRUM-150] Refact : 답글 글자수 제한 변경
  src/main/java/com/kkinikong/be/community/service/CommunityService.java
Labels: :recycle: Refactor

#69 [SCRUM-242] Refact : 닉네임 관련 api에서 응답 정보 추가
  src/main/java/com/kkinikong/be/user/dto/response/NicknameResponse.java
  src/main/java/com/kkinikong/be/user/service/UserService.java
Labels: :recycle: Refactor
